const unknownAccountEvidence = {
  account_type: "unknown",
  code_state: "unknown",
  observation_block_number: null,
  eip7702_delegation_target: null,
} as const;

const unknownEventEvidence = {
  counterparty_account_type: "unknown",
  counterparty_code_state: "unknown",
  counterparty_observation_block_number: null,
  counterparty_eip7702_delegation_target: null,
} as const;

const recognizedEvidence = {
  recognition_status: "recognized",
  recognition_override_status: null,
  counterparty_account_type: "unknown",
} as const;

const otherEvidence = {
  recognition_status: "other",
  recognition_override_status: null,
  counterparty_account_type: "unknown",
} as const;

export const summaries = {
  tokens: [
    {
      chain_id: 1,
      wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      token_address: "0x2",
      token_symbol: "USDC",
      token_name: "USD Coin",
      ...recognizedEvidence,
      transfer_count: 99,
      inbound_transfer_count: 98,
      outbound_transfer_count: 0,
      self_transfer_count: 1,
      indirect_inbound_transfer_count: 98,
      indirect_outbound_transfer_count: 0,
      counterparty_count: 1,
      sender_account_count: 1,
      recipient_account_count: 0,
    },
    {
      chain_id: 1, wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", token_address: "0x3", token_symbol: "OTHER",
      token_name: "Other Token",
      ...otherEvidence,
      transfer_count: 1, inbound_transfer_count: 1, outbound_transfer_count: 0,
      self_transfer_count: 0,
      indirect_inbound_transfer_count: 0, indirect_outbound_transfer_count: 0,
      counterparty_count: 1, sender_account_count: 1, recipient_account_count: 0,
    },
  ],
  counterparties: [
    {
      ...unknownAccountEvidence,
      chain_id: 1, wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      counterparty_address: "0x1111111111111111111111111111111111111111",
      recognition_status: "recognized", transfer_count: 98,
      inbound_transfer_count: 98, outbound_transfer_count: 0, token_count: 1,
      first_seen_at: "2023-11-14T22:15:00+00:00", last_seen_at: "2023-11-14T22:15:00+00:00",
    },
    {
      ...unknownAccountEvidence,
      chain_id: 1, wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      counterparty_address: "0x2222222222222222222222222222222222222222",
      recognition_status: "other", transfer_count: 1,
      inbound_transfer_count: 1, outbound_transfer_count: 0, token_count: 1,
      first_seen_at: "2023-11-14T22:16:00+00:00", last_seen_at: "2023-11-14T22:16:00+00:00",
    },
  ],
};

export const timeline = [
  { ...recognizedEvidence, chain_id: 1, wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", block_date: "2023-11-14", token_address: "0x2", token_symbol: "USDC", direction: "in", transfer_count: 98 },
  { ...recognizedEvidence, chain_id: 1, wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", block_date: "2023-11-14", token_address: "0x2", token_symbol: "USDC", direction: "self", transfer_count: 1 },
  { ...otherEvidence, chain_id: 1, wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", block_date: "2023-11-14", token_address: "0x3", token_symbol: "OTHER", direction: "in", transfer_count: 1 },
];

const events = [
  {
    ...unknownEventEvidence,
    transfer_id: "1-0xaaa-0",
    chain_id: 1,
    wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    block_number: 17_000_001,
    block_timestamp: "2023-11-14T22:15:00+00:00",
    transaction_hash: "0xaaa",
    transaction_index: 2,
    log_index: 0,
    direction: "in",
    is_indirect: true,
    counterparty_address: "0x1111111111111111111111111111111111111111",
    token_address: "0x2",
    token_symbol: "USDC",
    token_name: "USD Coin",
    ...recognizedEvidence,
  },
  {
    ...unknownEventEvidence,
    transfer_id: "1-0xother-0", chain_id: 1, block_number: 17_000_002,
    block_timestamp: "2023-11-14T22:16:00+00:00",
    transaction_hash: "0xother", transaction_index: 3, log_index: 0,
    wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", direction: "in",
    is_indirect: null,
    counterparty_address: "0x2222222222222222222222222222222222222222", token_address: "0x3",
    token_symbol: "OTHER", token_name: "Other Token",
    ...otherEvidence,
  },
];

export const dashboardEvents = [
  events[0],
  ...Array.from({ length: 98 }, (_, index) => ({
    ...events[0],
    transfer_id: `1-0xextra-${index}`,
    transaction_hash: `0xextra${index}`,
    log_index: index + 1,
    ...(index === 8 ? {
      transfer_id: "1-0xself-0",
      transaction_hash: "0xself",
      direction: "self",
      is_indirect: false,
      counterparty_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    } : {}),
  })),
  events[1],
];

export const metadata = {
  configured_wallet_label: "Example wallet",
  wallet_address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
  chain_id: 1,
  data_source: "fixture",
  generated_at: "2023-11-14T22:17:00+00:00",
  snapshot_run_id: "demo-run",
  snapshot_start_block: 0,
  snapshot_end_block: 25_739_543,
  snapshot_end_block_hash: "0x5374be585630353358d7c6a0b20106fc74c45577264cbe6a70ad8e4b0ed5f484",
  snapshot_finality_policy: "ethereum_finalized",
  snapshot_scope_version: "wallet-transfer-signature-v1",
  transfer_count: 100,
  event_block_number_min: 17_000_001,
  event_block_number_max: 17_000_002,
  first_event_at: "2023-11-14T22:15:00+00:00",
  last_event_at: "2023-11-14T22:16:00+00:00",
  account_evidence_population_scope: "distinct_nonzero_nonself_event_counterparties",
  account_evidence_eligible_address_count: 2,
  account_evidence_classified_address_count: 0,
  account_evidence_failed_address_count: 0,
  account_evidence_not_checked_address_count: 2,
  account_evidence_eligible_event_count: 99,
  account_evidence_classified_event_count: 0,
  account_evidence_failed_event_count: 0,
  account_evidence_not_checked_event_count: 99,
  account_evidence_observation_block_number_min: null,
  account_evidence_observation_block_number_max: null,
  account_evidence_observation_block_timestamp_min: null,
  account_evidence_observation_block_timestamp_max: null,
  account_evidence_schema_version: null,
  export_schema_version: "dashboard-export-v1",
  snapshot_source: "envio_hyperindex",
  snapshot_schema_version: "mainnet-demo-snapshot-v1",
  wallet_attribution_source_url: "https://manual.gitcoin.co/introduction-and-overview/dao-finances",
  completeness_scope: "finalized_block_range",
  indexer_checkpoint_recorded: true,
  finality_status: "finalized",
  complete_event_count: 100,
  complete_token_summary_row_count: 2,
  complete_counterparty_summary_row_count: 2,
  complete_timeline_row_count: 3,
  recognition_counts: {
    recognized: { transfer_count: 99, token_count: 1, counterparty_count: 1 },
    other: { transfer_count: 1, token_count: 1, counterparty_count: 1 },
    "recognized+other": { transfer_count: 100, token_count: 2, counterparty_count: 2 },
  },
  recognition_account_counts: {
    "recognized|eoa_candidate+contract": {
      transfer_count: 99,
      token_count: 1,
      counterparty_count: 1,
    },
    "recognized+other|eoa_candidate+contract": {
      transfer_count: 100,
      token_count: 2,
      counterparty_count: 2,
    },
  },
  exported_event_count: 100,
  exported_token_summary_count: 2,
  exported_counterparty_summary_count: 2,
  exported_timeline_row_count: 3,
  recognition_account_evidence_cell_count: 2,
  event_export_limit_per_recognition_account_evidence: 1000,
  token_summary_ranking_limit_per_recognition_account_selection: 500,
  token_summary_ranking_selection_count: 9,
  token_summary_ranking_candidate_token_count: 2,
  token_summary_rankings_exact_for_all_filter_selections: true,
  counterparty_ranking_limit_per_recognition_account_selection: 50,
  counterparty_recognition_combination_count: 3,
  counterparty_account_filter_combination_count: 3,
  counterparty_ranking_selection_count: 9,
  counterparty_ranking_candidate_address_count: 2,
  counterparty_rankings_exact_for_all_filter_selections: true,
  timeline_row_export_limit_per_recognition_account_evidence: 5000,
  is_sampled: false,
};
