{% if var('use_fixture', true) %}
select
  null::integer as chain_id,
  null::varchar as address,
  null::varchar as account_type,
  null::varchar as code_state,
  null::bigint as code_size_bytes,
  null::bigint as observation_block_number,
  null::varchar as observation_block_hash,
  null::varchar as observation_block_timestamp,
  null::varchar as eip7702_delegation_target,
  false as safe_verified,
  'not_collected'::varchar as safe_verification_status,
  null::varchar as safe_version,
  null::varchar as safe_singleton_address,
  null::integer as safe_owner_count,
  null::integer as safe_threshold,
  false as erc4337_observed,
  null::bigint as erc4337_user_operation_count,
  null::bigint as erc4337_first_observed_block,
  null::bigint as erc4337_last_observed_block,
  null::varchar as erc4337_entrypoint_address,
  null::varchar as erc4337_entrypoint_version,
  null::varchar as erc4337_entrypoint_source,
  null::varchar as erc4337_entrypoint_deployment_block,
  null::varchar as erc4337_effective_coverage,
  null::varchar as erc4337_failed_ranges,
  null::bigint as erc4337_block_chunk_size,
  null::integer as erc4337_address_batch_size,
  null::varchar as fetch_status,
  null::varchar as reason_codes,
  null::varchar as coverage_scope,
  null::bigint as coverage_start_block,
  null::bigint as coverage_end_block,
  null::varchar as evidence_schema_version,
  null::varchar as fetched_at
where false
{% else %}
select
  cast(chain_id as integer) as chain_id,
  lower(address) as address,
  account_type,
  code_state,
  code_size_bytes,
  observation_block_number,
  lower(observation_block_hash) as observation_block_hash,
  cast(observation_block_timestamp as varchar) as observation_block_timestamp,
  eip7702_delegation_target,
  false as safe_verified,
  'not_collected' as safe_verification_status,
  null::varchar as safe_version,
  null::varchar as safe_singleton_address,
  null::integer as safe_owner_count,
  null::integer as safe_threshold,
  false as erc4337_observed,
  null::bigint as erc4337_user_operation_count,
  null::bigint as erc4337_first_observed_block,
  null::bigint as erc4337_last_observed_block,
  null::varchar as erc4337_entrypoint_address,
  null::varchar as erc4337_entrypoint_version,
  null::varchar as erc4337_entrypoint_source,
  null::varchar as erc4337_entrypoint_deployment_block,
  null::varchar as erc4337_effective_coverage,
  null::varchar as erc4337_failed_ranges,
  null::bigint as erc4337_block_chunk_size,
  null::integer as erc4337_address_batch_size,
  fetch_status,
  reason_code as reason_codes,
  'all_distinct_event_counterparties' as coverage_scope,
  null::bigint as coverage_start_block,
  observation_block_number as coverage_end_block,
  evidence_schema_version,
  cast(fetched_at as varchar) as fetched_at
from account_evidence.account_evidence
{% endif %}
